clusters:
- name: minikube
  destinationServer: https://kubernetes.default.svc
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"

    sampleApp:
      enabled: true
      branch: HEAD

- name: gke
  destinationServer: https://34.68.112.194
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"
    sampleApp:
      enabled: true
      branch: HEAD
- name: gke
  destinationServer: https://35.222.92.169
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"
    sampleApp:
      enabled: true
      branch: HEAD
